name: sphinx_seva
channels:
  - https://anaconda.org/pytorch3d/pytorch3d/0.7.8/download
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.16=he870216_1
  - pytorch3d=0.7.8=py310_cu118_pyt241
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.1.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beartype==0.20.2
      - beautifulsoup4==4.13.4
      - bitsandbytes==0.47.0
      - black==25.1.0
      - blinker==1.9.0
      - browser-cookie3==0.20.1
      - certifi==2025.1.31
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - colorlog==6.9.0
      - colorspacious==1.1.2
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.2
      - cycler==0.12.1
      - dacite==1.9.2
      - dash==3.0.4
      - datasets==4.0.0
      - decorator==5.2.1
      - diffusers==0.32.2
      - dill==0.3.8
      - distlib==0.4.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - e3nn==0.5.6
      - einops==0.8.1
      - embreex==2.17.7.post6
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - facexlib==0.3.0
      - fastapi==0.115.12
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.13.1
      - filterpy==1.4.5
      - fire==0.7.0
      - flask==3.0.3
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.17.0
      - gradio-client==1.7.1
      - grpcio==1.74.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.3
      - hydra-core==1.3.2
      - icecream==2.1.5
      - identify==2.6.13
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - iniconfig==2.1.0
      - ipython==8.36.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jaxtyping==0.3.2
      - jedi==0.19.2
      - jeepney==0.9.0
      - jinja2==3.1.4
      - joblib==1.5.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - lmdb==1.7.3
      - lpips==0.1.4
      - lxml==5.3.1
      - lz4==4.4.4
      - manifold3d==3.0.1
      - mapbox-earcut==1.0.3
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - moviepy==2.1.2
      - mpmath==1.3.0
      - msgspec==0.19.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - narwhals==1.38.2
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.4
      - nodeenv==1.9.1
      - numba==0.61.2
      - numpy==2.2.5
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - open-clip-torch==2.31.0
      - open3d==0.19.0
      - openai-clip==1.0.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - orjson==3.10.16
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.8
      - plotly==6.0.1
      - pluggy==1.6.0
      - plyfile==1.1
      - pre-commit==4.3.0
      - proglog==0.1.11
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pycollada==0.9
      - pycryptodomex==3.22.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyiqa==0.1.14.1
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - pytest==8.4.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - retrying==1.3.4
      - rich==13.9.4
      - roma==1.5.2.1
      - rpds-py==0.23.1
      - rtree==1.4.0
      - ruff==0.11.2
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - selenium==4.32.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - seva==0.0.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - shtab==1.7.1
      - six==1.17.0
      - sk-video==1.1.10
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - splines==0.3.2
      - stack-data==0.6.3
      - starlette==0.46.1
      - svg-path==6.3
      - svg-py==1.6.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - timm==1.0.15
      - tokenizers==0.15.2
      - tomli==2.2.1
      - tomlkit==0.13.2
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchmetrics==1.7.1
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.37.2
      - trimesh==4.6.5
      - trio==0.30.0
      - trio-websocket==0.12.2
      - triton==3.2.0
      - typeguard==4.4.2
      - typer==0.15.2
      - typing-extensions==4.14.1
      - tyro==0.9.17
      - tzdata==2025.2
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - vhacdx==0.0.8.post2
      - virtualenv==20.34.0
      - viser==0.2.23
      - wadler-lindig==0.1.5
      - wandb==0.19.11
      - wcwidth==0.2.13
      - websocket-client==1.8.0
      - websockets==14.2
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - wsproto==1.2.0
      - xatlas==0.0.9
      - xlsxwriter==3.2.5
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.20.0
      - yourdfpy==0.0.57
      - youtube-dl==2021.12.17
      - yt-dlp==2025.4.30
      - zipp==3.21.0
